dist: trusty
language: perl
perl:
- '5.22'    # because there's no 5.22.2 :(
- '5.20.3'
- '5.18.2'  # because it's all that seems to be available
before_install:
- git clone git://github.com/haarg/perl-travis-helper
- source perl-travis-helper/init
- build-perl
- perl -V
- cpan-install Dist::Zilla~6.008
- git config --global user.email "travis.ci@chizography.net"
- git config --global user.name "Travis CI"
- build-dist
- cd $BUILD_DIR
install:
- export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=c
  HARNESS_TIMER=1
- cpanm --quiet --notest Devel::Cover::Report::Coveralls
- cpanm --quiet --notest --installdeps .
script:
- PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove
  -lrsv t
- cover
after_success:
- cover -report coveralls
notifications:
  slack:
    secure: F0eeMMZ5hv9ntOKfztHt9Xx0Pzqo1F2lOntx4j7k3fWYYhL9taUeN8gn/2TT3f2kne30S3UXjil3J4bWf9DXHydnaIxI+JHz/1etSImLJbXhjW1DneZqYhKee/CipmoxS6iiEsVrs28OqDgkkE6msw108uZH7UbXX5wyVd+eici8/H0iPmeTs1eTtOkLI4s3yCdyC3qV7GrQq05hnKSGiuiAnmTvnr+QhJ8lzN1tb7BxNjPkY9qvsMH5IxIQp6a0Ypk/pYQHuoHG7Bm44rGcRJ0DP2yxwCT4JsAC2WqTCyH8/cm7+wKuWAPGu5lLOHkhmsv9YjjMrrI2R9qRPqO0RJ+VJIuhfgr9ILcSyhqW96OlUvttWIdCNNYTXmrIJLSmmL70hJDthJBgZcH+Yg9G6vtHOVLyrNbSWi4+xptSghQjUijPI9SIMKLHWoSGarLAccQGAnqP/6WrQzdy8oqQV2mAnsNayY7Naef9qLOLX2dGPjUGP53yTNHsR5SZVAwWXo5V84P2gcT+qezxOI300g9udyJu78avuZg3x1X68BFRoxvMoeMg9g78u6/rY4RYdk8k4WSrSoMgdW+0Prq5jVWQGcqz8nr5FIBeCIolHAOt/sDFnhQP9pfemzmNj7dijgtw/8Q8Vm8bskMEHP9qEdj5HVMFRNm/pBNLJEfolMc=
matrix:
  allow_failures:
    - perl: blead       # ignore failures for blead perl
